import os
import pymummer
from operator import attrgetter
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
import shutil
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

configfile: "../config.yaml"

FASTAFILES = [os.path.basename(el[0]) for el in pd.read_csv(config["genomes_list"], header=None).values]
FASTAEXT = {os.path.splitext(el)[0]:os.path.splitext(el)[1] for el in FASTAFILES}
GENOMES = list(FASTAEXT.keys())
FASTAPATH = config["fastas"]
OUTPUTPATH = config["output_dir"]
COMMUNITIESPATH = config["communities"]
PREFIX = config["prefix"]

def get_community_to_plasmid():
    community_to_plasmid = {}
    communities = []
    with open(COMMUNITIESPATH) as communities_fh:
        for community_index, line in enumerate(communities_fh):
            plasmids = line.strip().split()
            community_to_plasmid[str(community_index)] = plasmids
            communities.append(community_index)
    return community_to_plasmid, communities

COMMUNITY_TO_PLASMID, COMMUNITIES = get_community_to_plasmid()

rule all:
    input:
        dedup_unimog = expand(f"{OUTPUTPATH}/unimogs/relabelled/dedup/{{community}}_dedup.unimog", community=COMMUNITIES),
        blocks_unimog = expand(f"{OUTPUTPATH}/unimogs/relabelled/blocks/{{community}}_blocks.unimog", community=COMMUNITIES),
        blocks_map = expand(f"{OUTPUTPATH}/unimogs/relabelled/blocks/{{community}}_map_blocks.txt", community=COMMUNITIES)

rule ggcaller:
    input:
        fasta_list = config["genomes_list"]
    output:
        ann_dir = directory(f"{OUTPUTPATH}/annotation/{{community}}")
    conda:
        "ggc_env"
    threads: 1 #default
    shell:
        "ggcaller --reads {input.fasta_list} --out {output.ann_dir}"

rule consolidation:
    input:
        lambda wildcards: expand(f"{OUTPUTPATH}/tmp_files/minimap/{wildcards.community}/output/{{genome}}.paf", genome=COMMUNITY_TO_PLASMID[wildcards.community]),
    output:
        unimog = f"{OUTPUTPATH}/unimogs/{{community}}_anno.unimog",
        map = f"{OUTPUTPATH}/unimogs/{{community}}_map.txt"
    threads: 1
    resources:
        mem_mb = lambda wildcards, attempt: attempt * 1000
    params:
        pafs=f"{OUTPUTPATH}/tmp_files/minimap/{{community}}/output",
        genomes = lambda wildcards: COMMUNITY_TO_PLASMID[wildcards.community],
        outputpath = OUTPUTPATH
    script:
        "consolidation.py"

'''
rule gen_dedup_input:
    input:
        lambda wildcards: expand(f"{FASTAPATH}/{{genome}}FASTAEXT[{genome}]", genome=COMMUNITY_TO_PLASMID[wildcards.community])
    output:
        f"{OUTPUTPATH}/tmp_files/community_fastas/{{community}}.fna"
    threads: 1
    resources:
        mem_mb = lambda wildcards, attempt: attempt * 1000
    shell:
        "cat {input} > {output}"

rule deduplication:
    input:
        fasta = f"{OUTPUTPATH}/tmp_files/community_fastas/{{community}}.fna",
        unimog = f"{OUTPUTPATH}/unimogs/{{community}}_anno.unimog",
        map = f"{OUTPUTPATH}/unimogs/{{community}}_map.txt"
    output:
        nucmer = f"{OUTPUTPATH}/tmp_files/nucmer/{{community}}.nucmer",
        relabelled_unimog = f"{OUTPUTPATH}/unimogs/relabelled/dedup/{{community}}_dedup.unimog",
        dedup_map = f"{OUTPUTPATH}/unimogs/relabelled/dedup/{{community}}_map_dedup.txt"
    threads: 1
    resources:
        mem_mb = lambda wildcards, attempt: attempt * 1000
    params:
        pafs=f"{OUTPUTPATH}/tmp_files/minimap/{{community}}/output",
        nucmer_threshold=config["dedup_threshold"],
        genomes = lambda wildcards: COMMUNITY_TO_PLASMID[wildcards.community]
    script:
        "multipartite.py"
'''

rule blocks:
    input:
        map = f"{OUTPUTPATH}/unimogs/relabelled/dedup/{{community}}_map_dedup.txt",
        unimog = f"{OUTPUTPATH}/unimogs/relabelled/dedup/{{community}}_dedup.unimog"
    output:
        relabelled_unimog = f"{OUTPUTPATH}/unimogs/relabelled/blocks/{{community}}_blocks.unimog",
        blocks_map = f"{OUTPUTPATH}/unimogs/relabelled/blocks/{{community}}_map_blocks.txt"
    threads: 1
    resources:
        mem_mb = lambda wildcards, attempt: attempt * 1000
    params:
        genomes = lambda wildcards: COMMUNITY_TO_PLASMID[wildcards.community],
        relabelled_dir = f"{OUTPUTPATH}/unimogs/relabelled/blocks"
    script:
        "blocks.py"
