name: Test pling

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.9, "3.10", 3.11 ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.4.5-0'
          environment-name: test-env
          condarc: |
            channels:
              - conda-forge
              - bioconda
              - defaults
          create-args: >-
            python=${{ matrix.python-version }}
            sourmash 
            pandas
            numpy
            intervaltree
            mummer=3.23
            glpk=5.0
            snakemake=7.32.4
            plasnet=0.6.0
            dingII
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.7.1

      - name: Test
        shell: bash -el {0}
        run: |
          micromamba deactivate
          micromamba activate test-env
          python -m pip install .
          PYTHONPATH="." python -m unittest discover -s tests -t .
